//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Overture.Hattusa.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class F1Entities : DbContext
    {
        public F1Entities()
            : base("name=F1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<GrandPrix> GrandPrixes { get; set; }
        public virtual DbSet<Lap> Laps { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<RaceEvent> RaceEvents { get; set; }
        public virtual DbSet<RaceEventType> RaceEventTypes { get; set; }
        public virtual DbSet<RaceResult> RaceResults { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TeamBase> TeamBases { get; set; }
        public virtual DbSet<TeamName> TeamNames { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
    }
}
