//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Overture.Hattusa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lap
    {
        public int RaceId { get; set; }
        public short LapId { get; set; }
        public int CarId { get; set; }
        public Nullable<long> TimeTicks { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Race Race { get; set; }
    }
}
